# **CSV Module:**

## **Writing CSV files:**

In [ ]:
import csv

with open('output.csv', 'w', newline='') as file:
    csv_writer = csv.writer(file)
    csv_writer.writerow(['Name', 'Age'])
    csv_writer.writerow(['Alice', 25])


## **Reading CSV files:**


In [ ]:
import csv

with open('output.csv', 'r') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        print(row)


['Name', 'Age']
['Alice', '25']


# **Pickle Module:**

## **Pickling Data:**

In [ ]:
import pickle

data = {'name': 'Alice', 'age': 30, 'id': 36526}
with open('dict_data.pkl', 'wb') as file:
    pickle.dump(data, file)


## **Unpickling Data:**

In [ ]:
import pickle

with open('dict_data.pkl', 'rb') as file:
    loaded_data = pickle.load(file)
    print(loaded_data)


{'name': 'Alice', 'age': 30, 'id': 36526}


## **Pickling and Unpickling Lists and Complex Structures:**

In [ ]:
import pickle

complex_data = [{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 25}]
with open('/content/sample_data/complex_data.pkl', 'wb') as file:
    pickle.dump(complex_data, file)

with open('/content/sample_data/complex_data.pkl', 'rb') as file:
    loaded_complex_data = pickle.load(file)
    print(loaded_complex_data)


[{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 25}]


# **re Module (Regular Expressions):**

In [ ]:
# Basic Pattern Matching:

import re

pattern = r"apple"
# print(type(pattern))
text = "I love apples."

match = re.search(pattern, text)
print("match", match)
if match:
    print("Pattern found:", match.group())


match <re.Match object; span=(7, 12), match='apple'>
Pattern found: apple


In [ ]:
# Replacing and Substituting:

import re

pattern = r"apple"
text = "I like apples and applesauce."

replaced_text = re.sub(pattern, "banana", text)
print(replaced_text)


I like bananas and bananasauce.


## **Metacharacters in re:**

In [ ]:
"""
[]	A set of characters	"[a-m]"
\	Signals a special sequence (can also be used to escape special characters)	"\d"
.	Any character (except newline character)	"he..o"
^	Starts with	"^hello"
$	Ends with	"planet$"
*	Zero or more occurrences	"he.*o"
+	One or more occurrences	"he.+o"
?	Zero or one occurrences	"he.?o"
{}	Exactly the specified number of occurrences	"he.{2}o"
|	Either or	"falls|stays"
()	Capture and group
"""

In [ ]:
# Using Metacharacters:

import re

pattern = r"^Hello.*world$"
text = "Hello, beautiful world"

if re.match(pattern, text):
    print("Pattern matched!")
else:
  print("not matched!")


Pattern matched!


In [ ]:
# Grouping and Capturing:

import re

pattern = r"(\d{2})-(\d{2})-(\d{4})"
text = "Date of birth: 10-12-3005"

dob_match = re.search(pattern, text)
if dob_match:
    print("Day:", dob_match.group(1))
    print("Month:", dob_match.group(2))
    print("Year:", dob_match.group(3))


Day: 10
Month: 12
Year: 3005


In [ ]:
# Splitting Strings:

import re

pattern = r"\s+"  # Split on whitespace
text = "Hello   World"

parts = re.split(pattern, text)
print(parts)


['Hello', 'World']


# **Numpy Module:**

## **Creating Arrays:**
  Creating 1D, 2D, and multi-dimensional arrays.

In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 'a', 4, 7])

print(arr_1d)
print(type(arr_1d))
print(arr_1d.shape)


['1' '2' 'a' '4' '7']
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print(type(arr_2d))
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
"""
1, 2, 3, 4
4, 5, 6, 5
7, 8, 9, 10
"""

In [ ]:
arr_3d = np.array([[[1, 2, 3], [4,5, 6]]])
print(arr_3d)
print(type(arr_3d))
print(arr_3d.shape)

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(1, 2, 3)


## **Array Attributes:**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Number of Elements:", arr.size)


Shape: (2, 3)
Data Type: int64
Number of Elements: 6


## **Array Initialization Functions:**

  Using functions like np.zeros(), np.ones(), np.arange(), and np.linspace() to create arrays.

In [ ]:
import numpy as np

zeros_arr = np.zeros((2, 3))
print(zeros_arr)
zeros_arr.dtype

[[0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [ ]:

ones_arr = np.ones((2, 3))
print(ones_arr)
ones_arr.dtype

[[1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [ ]:

range_arr = np.arange(0, 10, 2)
print(range_arr)
print(range_arr.dtype)


[0 2 4 6 8]
int64


In [ ]:

linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


## **Array Indexing and Slicing:**


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("First element:", arr[0])
print("Second:", arr[1])

print("Slice:", arr[1:4])

arr[2] = 6

print(arr)



First element: 1
Second: 2
Slice: [2 3 4]
[1 2 6 4 5]


## **Array Operations:**

Performing element-wise arithmetic operations on arrays.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


sum_arr = arr1 + arr2
print("SUM:", sum_arr)

product_arr = arr1  * arr2
print("PRODUCT:", product_arr)


SUM: [5 7 9]
PRODUCT: [ 4 10 18]


## **Array Broadcasting:**

Understanding how NumPy handles operations on arrays of different shapes.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print("arr\n", arr)
scalar = 2
scaled_arr = arr * scalar

print("scaled_arr\n", scaled_arr)


(2, 3)
arr
 [[1 2 3]
 [4 5 6]]
scaled_arr
 [[ 2  4  6]
 [ 8 10 12]]


## **Array Functions and Methods:**

Exploring functions like np.sum(), np.mean(), np.max() and methods like arr.reshape(), arr.flatten().

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape before:", arr.shape)
print("Array:\n", arr)

total_sum = np.sum(arr)
print("Sum:", total_sum)

mean_value = np.mean(arr)
print("Mean:", mean_value)

max_value = np.max(arr)
print("Max:", max_value)

min_value = np.min(arr)
print("Min:", min_value)

reshaped_arr = arr.reshape(3, 2)
print("Shape after reshaped:\n", reshaped_arr)

flattened_arr = arr.flatten()
print("Flatten Array:", flattened_arr)


Shape before: (2, 3)
Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Mean: 3.5
Max: 6
Min: 1
Shape after reshaped:
 [[1 2]
 [3 4]
 [5 6]]
Flatten Array: [1 2 3 4 5 6]


## **Array Aggregation and Reduction:**

Using aggregation functions like np.sum(), np.prod(), np.min(), and np.max().

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(arr)
product = np.prod(arr)
print("arr product:", product)
min_val = np.min(arr)
max_val = np.max(arr)
print("arr sum:", total_sum)
print("arr min:", min_val)
print("arr max:", max_val)


arr product: 720
arr sum: 21
arr min: 1
arr max: 6


## **Array Reshaping and Transposing:**

Changing the shape and structure of arrays.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array before:\n", arr)
transposed_arr = arr.T
print("Array after Transposed:\n", transposed_arr)

flattened_arr = arr.ravel()
print("flattened_arr:\n", flattened_arr)


Array before:
 [[1 2 3]
 [4 5 6]]
Array after Transposed:
 [[1 4]
 [2 5]
 [3 6]]
flattened_arr:
 [1 2 3 4 5 6]


## **Array Sorting:**

Sorting elements in arrays.

In [ ]:
import numpy as np

arr = np.array([4, 2, 5, 1, 3])

sorted_arr = np.sort(arr)
print("sorted_arr:\n", sorted_arr)


sorted_arr:
 [1 2 3 4 5]


In [ ]:
arr = np.array([[4, 2, 5], [1, 8, 0]])

sorted_arr = np.sort(arr)
print("sorted_arr:\n", sorted_arr)


sorted_arr:
 [[2 4 5]
 [0 1 8]]


# **File Operations in Python:**

## **Creating a File:**
We can create a new file using the open() function with the "w" mode (write mode). If the file already exists, this will overwrite its contents.


In [ ]:
file_path = "abc.txt"

with open(file_path, "w") as f:
    f.write("Hello, my name is Anjana.")


## **Reading from a File:**
We can read the contents of a file using the open() function with the "r" mode (read mode).



In [ ]:
file_path = "sample_data/anscombe.json"

with open(file_path, "r") as file:
    content = file.read()
    print(content)


[
  {"Series":"I", "X":10.0, "Y":8.04},
  {"Series":"I", "X":8.0, "Y":6.95},
  {"Series":"I", "X":13.0, "Y":7.58},
  {"Series":"I", "X":9.0, "Y":8.81},
  {"Series":"I", "X":11.0, "Y":8.33},
  {"Series":"I", "X":14.0, "Y":9.96},
  {"Series":"I", "X":6.0, "Y":7.24},
  {"Series":"I", "X":4.0, "Y":4.26},
  {"Series":"I", "X":12.0, "Y":10.84},
  {"Series":"I", "X":7.0, "Y":4.81},
  {"Series":"I", "X":5.0, "Y":5.68},

  {"Series":"II", "X":10.0, "Y":9.14},
  {"Series":"II", "X":8.0, "Y":8.14},
  {"Series":"II", "X":13.0, "Y":8.74},
  {"Series":"II", "X":9.0, "Y":8.77},
  {"Series":"II", "X":11.0, "Y":9.26},
  {"Series":"II", "X":14.0, "Y":8.10},
  {"Series":"II", "X":6.0, "Y":6.13},
  {"Series":"II", "X":4.0, "Y":3.10},
  {"Series":"II", "X":12.0, "Y":9.13},
  {"Series":"II", "X":7.0, "Y":7.26},
  {"Series":"II", "X":5.0, "Y":4.74},

  {"Series":"III", "X":10.0, "Y":7.46},
  {"Series":"III", "X":8.0, "Y":6.77},
  {"Series":"III", "X":13.0, "Y":12.74},
  {"Series":"III", "X":9.0, "Y":7.11},
 

## **Writing to a File:**
To append new content to an existing file without overwriting its current content, use the "a" mode (append mode).

In [ ]:
file_path = "example.txt"
with open(file_path, "a") as file:
    file.write("\nI live in UK.")


## **Deleting a File:**
We can delete a file using the os.remove() function from the os module.

**NOTE:** Remember to handle exceptions, like FileNotFoundError and PermissionError, that might occur during these operations. Always use 'with statements' when working with files, they ensure that the file is properly closed after use.

In [ ]:
import os

file_path = "abc.txt"
if os.path.exists(file_path):
    os.remove(file_path)
    print(f"{file_path} has been deleted.")
else:
    print(f"{file_path} doesn't exist.")


abc.txt has been deleted.


## **Reading File Line by Line:**
We can read a file line by line using a loop. This is useful for processing large files without loading the entire content into memory.

In [ ]:
file_path = "example.txt"
with open(file_path, "r") as file:
    for line in file:
        print(line.strip())   # strip() removes the newline character



Hello, my name is Anjana.
I live in UK.
She is Jyotsna, She lives in USA.


## **Reading and Writing Binary Files:**
We can work with binary files by using the "rb" mode (read binary) for reading and the "wb" mode (write binary) for writing.

In [ ]:
# Reading binary file
binary_file_path = "image.jpeg"
with open(binary_file_path, "rb") as file:
    binary_data = file.read()
    print("binary_data: ", binary_data)
    # Process binary_data

# # Writing binary file
output_path = "new_text_file.txt"
with open(output_path, "wb") as file:
    file.write(b'{"a":1,"b":2}')  # Write binary data back


binary_data:  b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d\x1a\x1c\x1c $.\' ",#\x1c\x1c(7),01444\x1f\'9=82<.342\xff\xdb\x00C\x01\t\t\t\x0c\x0b\x0c\x18\r\r\x182!\x1c!22222222222222222222222222222222222222222222222222\xff\xc2\x00\x11\x08\x04\x00\x02\xe4\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1a\x00\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x03\x04\x01\x05\x06\xff\xc4\x00\x18\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\xff\xda\x00\x0c\x03\x01\x00\x02\x10\x03\x10\x00\x00\x02\xacc\xc4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0b\xca\x1e\x9f\x98\xa0\x80\x00\x00\x00\x00\x00\x00=/7\xd4\xbb\x86\x1fB\x0b\x92\xafO\x89\x86\x1bj\x92\xfc^\x8cn\xfc\xf9]\xb5\x9f+\x

## **Reading and Writing CSV Files:**
csv module can be used for reading and writing CSV (Comma-Separated Values) files.

In [ ]:
import csv

csv_file_path = "data.csv"

# Writing CSV
data = [
    ["Name", "Age"],
    ["Alice", 25],
    ["Bob", 30],
]
with open(csv_file_path, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)



In [ ]:
# Reading CSV
with open(csv_file_path, "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)


['Name', 'Age']
['Alice', '25']
['Bob', '30']


## **Working with JSON Files:**
Python's json module is useful for reading and writing JSON files.

In [ ]:
import json

json_file_path = "data.json"

# Writing JSON
data = {"name": "Alice", "age": 25}
with open(json_file_path, "w") as file:
    json.dump(data, file)



In [ ]:
# Reading JSON
with open(json_file_path, "r") as file:
    loaded_data = json.load(file)
    print(loaded_data)


{'name': 'Alice', 'age': 25}


## **Renaming and Moving Files:**
We can use os.rename() to rename files and shutil.move() to move files.

In [ ]:
import os
import shutil

old_file_path = "data.json"
new_file_path = "json_data.json"

os.rename(old_file_path, new_file_path)  # Rename file



In [ ]:
# /content/sample_data.json

In [ ]:
source_path = "json_data.json"
destination_path = "sample_data/json_data.json"
shutil.move(source_path, destination_path)  # Move file


'sample_data/json_data.json'

# **Break Keyword:**

break keyword in Python is used to exit or terminate a loop prematurely. It's commonly used in loops to immediately stop the loop's execution when a certain condition is met.

In [ ]:
# Program to find the first even number in a list
numbers = [3, 7, 12, 5, 9, 16, 20]

count = 0
for num in numbers:
    if num % 2 == 0:
        count += 1
        print(f"{count} Even number found:", num)
        if count == 2:
          break


1 Even number found: 12
2 Even number found: 16


# **Some Important Functions: map(), filter(), reduce(), and zip():**

## **map() Function:**

The map() function applies a given function to all items in an iterable (such as a list) and returns an iterator with the results.

In [ ]:
from posixpath import lexists
numbers = [1, 2, 3, 4, 5] # sequence or iterable

# a = "giuueghu"

def square(x):
    return x ** 2

# def str_upper(x):
#   return x.upper()

squared_numbers = map(square, numbers)
print(squared_numbers)
squared_list = list(squared_numbers)
print(squared_list)  # Output: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]


In [ ]:
# Using map() with Lambda:

numbers = [1, 2, 3, 4, 5]

cube_numbers = map(lambda x: x ** 3, numbers)
cube_list = list(cube_numbers)
print(cube_list)


[1, 8, 27, 64, 125]


## **filter() Function:**

The filter() function filters out elements from an iterable based on a given function's condition.

In [ ]:
# Filter even numbers

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def is_even(x):
    return x % 2 == 0

even_numbers = filter(is_even, numbers)
even_list = list(even_numbers)
print(even_list)  # Output: [2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]


In [ ]:
# Filter odd numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

odd_numbers = filter(lambda x: x % 2 != 0, numbers)
odd_list = list(odd_numbers)
print(odd_list)



[1, 3, 5, 7, 9]


## **reduce() Function:**

The reduce() function from the functools module continuously applies a binary function to the items of a sequence, reducing the sequence to a single value.

In [ ]:
from functools import reduce

numbers = [1, 2, 3, 4, 5]

def multiply(x, y):
    return x * y

product = reduce(multiply, numbers)
print(product)  # Output: 120


120


In [ ]:
from functools import reduce

numbers = [1, 2, 3, 4, 5]

total_sum = reduce(lambda x, y: x + y, numbers)
print(total_sum)


15


## **zip() Function:**

The zip() function aggregates elements from multiple iterables into tuples, creating an iterator that can be used for parallel iteration.

In [ ]:
names = ["Alice", "Bob", "Charlie"]
scores = [95, 82, 78]
cities = ['Jaipur', 'Delhi', 'Hyderabad']

zipped = zip(names, scores, cities)
print(zipped)
zipped_list = list(zipped)
print(zipped_list)  # Output: [('Alice', 95), ('Bob', 82), ('Charlie', 78)]


[('Alice', 95, 'Jaipur'), ('Bob', 82, 'Delhi'), ('Charlie', 78, 'Hyderabad')]


# **Iterators:**

An iterator in Python is an object that allows you to loop over a sequence of values, one at a time. It follows a specific protocol, providing the __iter__() method that returns itself and the __next__() method that fetches the next value in the sequence. When there are no more items to iterate, it raises a StopIteration exception.

Note: It is similar to for loop when we iterate over a sequence one by one.



In [ ]:
# Iterator Example
numbers = [1, 2, 3, 4, 5]

iterator = iter(numbers)
print(iterator)
print(next(iterator))
print(next(iterator))
print(next(iterator))
print(next(iterator))
print(next(iterator))

print(next(iterator))



1
2
3
4
5


StopIteration: ignored

In [ ]:
numbers = [1, 2, 3, 4, 5]

iterator = iter(numbers)

while True:
    try:
        value = next(iterator)
        print(value)
    except StopIteration:
        break



1
2
3
4
5


# **Generators:**

Generators in Python are a concise way to create iterables (sequence). They are functions that use the yield keyword to produce values on-the-fly. Instead of generating all values upfront and storing them in memory, generators produce values lazily as they are needed. This makes them memory-efficient and suitable for handling large datasets or infinite sequences.

In [ ]:
# Generator Example without OOP
def my_generator(max_value):
    current = 0
    while current < max_value:
        yield current
        current += 1

gen = my_generator(5)
print(gen)


for num in gen:
    print(num)


<generator object my_generator at 0x7fe82f147920>
0
1
2
3
4


## **Generator function VS a regular function:**



In [ ]:
def square_numbers(numbers):
    result = []
    for num in numbers:
        result.append(num ** 2)
    return result

numbers = [1, 2, 3, 4, 5]
squared = square_numbers(numbers)
print(squared)  # Output: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]


In [ ]:
def square_numbers_generator(numbers):
    for num in numbers:
        yield num ** 2

numbers = [1, 2, 3, 4, 5]
squared_gen = square_numbers_generator(numbers)
print(squared_gen)

for squared_num in squared_gen:
    print(squared_num)


<generator object square_numbers_generator at 0x7fe82f147b50>
1
4
9
16
25


---
# **Questions to practice:**

1. Consider the list of dictionaries representing books, like this:

  books = [
      {"Title": "The Great Gatsby", "Author": "F. Scott Fitzgerald", "Year": 1925},
      {"Title": "To Kill a Mockingbird", "Author": "Harper Lee", "Year": 1960},
      {"Title": "1984", "Author": "George Orwell", "Year": 1949}
  ]

  Write a Python program using the csv module to write this list of dictionaries to a CSV file named "books.csv".

2. Suppose you have a CSV file named "data.csv" with the following content:

  Name,Age,Location

  Alice,28,New York

  Bob,32,San Francisco

  Carol,25,Los Angeles

  Write a Python program using the csv module to read this file and print each row as a dictionary.

3. Consider a list of integers: [1, 2, 3, 4, 5]. Write Python program to pickle this list into a file named "numbers.pkl" and then unpickle it to retrieve and print the list.

4. Consider a dictionary of student names and their corresponding ages: {"Alice": 25, "Bob": 28, "Carol": 22}. Write Python code to pickle this dictionary into a file named "students.pkl" and then unpickle it to retrieve and print the dictionary.

5. Write a Python program that uses the re module to match and print all occurrences of the word "cat" in a given text. For example, given the text:

  "The cat sat on the mat and watched another cat playing with a ball of yarn."

6. Given a string containing phone numbers in the format "XXX-XXX-XXXX", write python code that uses the re module to extract and print all the phone numbers from the string. For example:

  "Contact us at 555-123-4567 or 888-555-7890 for assistance."



7. Write a Python program that uses the re.sub() function to mask sensitive information such as credit card numbers in a given text. Replace all occurrences of credit card numbers in the format "XXXX-XXXX-XXXX-XXXX" with "--****-XXXX". Check below example:

In [ ]:
input_text = "Please provide your credit card number: 1234-5678-9012-3456"

output_text = "Please provide your credit card number: ****-****-****-3456"

# code here

8. Write a python program that uses the re module to match and print all occurrences of digits (0-9) in a given text.

  For example, given the text:

  "The price of the product is $159.09."
  
  Output = 15909

9. Write a python program that uses the re module to match and print all words that start with the letter "a" and end with the letter "e" in a given text.

  For example, given the text:

  "Apple, banana, and orange are some fruits."
  

---
# **Questions to practice:**

1. Create a 1D numpy array with integers from 5 to 15.

2. Construct a 1D array of 15 equally spaced values between -1 and 1.

3. Create a 2D numpy array of size 4x5 filled with ones.

4. Create a 3D array with dimensions (2, 3, 4) and how to find the total Number of Elements in that 3D array.

5. Create a 2D numpy array with dimensions 4x6, filled with zeros.

6. Create a numpy array with integers from 0 to 9. Use slicing to extract the subarray [3, 4, 5].

7. Given a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]], use slicing to extract the subarray [[2, 3], [5, 6]].

8. Create two 1D arrays [1, 2, 3] and [4, 5, 6]. Perform element-wise addition on them.

9. Multiply the array [2, 4, 6, 8] by a scalar value of 3.

10. Subtract the array [10, 20, 30, 40] by the array [1, 2, 3, 4].

11. Calculate the dot product of two arrays: [1, 2, 3] and [4, 5, 6] i. e. (Arr1 * Arr2).

12. Create a numpy array [5, 10, 15, 20, 25] and calculate its sum, mean, and maximum value using numpy functions.

13. Create a 2D array with dimensions 4x5, reshape it into a 1D array using the flatten() method. Calculate the product of all elements in the original 2D array and the flattened array.

14. Create a 2D array of size 3x4. Transpose the array using the .T attribute and then flatten it using the ravel() method. Sort the flattened array in ascending order.

15. Create a text file named "data.txt" and write the numbers 1 to 10, each on a new line.

16. Read the content of "data.txt" file line by line and print each line.

17. Open the "data.txt" file in append mode and add numbers 11 to 15 at the end of the file.

18. Delete the "data.txt" file that we have created in earlier questions.

19. Generate a list of integers [10, 20, 30, 40] and write it as binary data to a file.

20. Read a binary file named "integers.bin" and convert it back to normal list.





---
# **Questions to practice:**

1. Write a Python program that renames a file named "old_filename.txt" to "new_filename.txt".

2. Write a Python program that moves a file named "data.txt" from the current directory to a subdirectory named "destination_folder".

3. Write a Python program that takes input from the user until they enter the word "exit". Use a loop and the break statement to terminate the loop when the user enters "exit".

4. Write a Python program that searches for a specific number in a list of numbers. Use a loop with the break statement to stop searching as soon as the number is found.

  Example:
  
  numbers = [5, 10, 15, 20, 25, 30]

  target_number = 20


5. Given a list of strings, use the map() function to create a new list containing the lengths of each string.

6. Create a program that takes a list of numbers and uses the map() function to calculate cube of each number.

7. Use the reduce() function to find the sum of numbers in a list.

8. Write a program that calculates the factorial of a given number using the reduce() function.

9. Given a list of numbers, use the filter() function to create a new list containing only the even numbers.

10. Given a list of words, use the filter() function to create a new list containing words with a length greater than 5 characters.

11. Given two lists, one containing names and the other containing ages, use the zip() function to create pairs of names and ages.

12. We have a list of student names and their corresponding scores. Use the zip() function to create a list of tuples where each tuple contains the student's name and their grade (A, B, C, or D) based on the score.

13. Create a Generator that generates square numbers from 1 to 15.

14. Create a Generator that generates even numbers starting from 2 to 20.

15. Create an iterator that generates individual words from a sentence "Python is a programming language". Use the iter() and next() methods to iterate through the words.

16. Create an iterator that generates individual words from a list of words. Use the iter() and next() methods to iterate through the list of words.




